import { jsPDF } from 'jspdf';

function safe(value) {
  return value === undefined || value === null || value === '' ? '-' : String(value);
}

export function exportCampusReport({
  title = 'CampusMate Report',
  generatedBy = 'CampusMate',
  summary = [],
  columns = [],
  rows = [],
  fileName = 'campusmate-report.pdf',
}) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const width = doc.internal.pageSize.getWidth();
  let y = 46;

  doc.setFillColor(7, 12, 26);
  doc.rect(0, 0, width, 96, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.text('CampusMate', 40, 42);
  doc.setFontSize(14);
  doc.text(title, 40, 70);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text(`Generated by ${generatedBy} on ${new Date().toLocaleString()}`, 40, 86);

  y = 128;
  if (summary.length) {
    doc.setTextColor(15, 23, 42);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.text('Summary', 40, y);
    y += 18;
    summary.forEach((item) => {
      doc.setFillColor(239, 246, 255);
      doc.roundedRect(40, y, width - 80, 28, 6, 6, 'F');
      doc.setTextColor(15, 23, 42);
      doc.setFont('helvetica', 'bold');
      doc.text(`${safe(item.label)}:`, 52, y + 18);
      doc.setFont('helvetica', 'normal');
      doc.text(safe(item.value), 160, y + 18, { maxWidth: width - 220 });
      y += 36;
    });
    y += 10;
  }

  if (columns.length && rows.length) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(15, 23, 42);
    doc.text('Details', 40, y);
    y += 22;
    const colWidth = (width - 80) / columns.length;
    doc.setFillColor(15, 23, 42);
    doc.rect(40, y, width - 80, 24, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(8);
    columns.forEach((column, index) => {
      doc.text(safe(column.label), 48 + index * colWidth, y + 16, {
        maxWidth: colWidth - 10,
      });
    });
    y += 24;

    rows.slice(0, 36).forEach((row, rowIndex) => {
      if (y > 760) {
        doc.addPage();
        y = 48;
      }
      doc.setFillColor(rowIndex % 2 === 0 ? 248 : 241, 245, 249);
      doc.rect(40, y, width - 80, 30, 'F');
      doc.setTextColor(30, 41, 59);
      doc.setFont('helvetica', 'normal');
      columns.forEach((column, index) => {
        doc.text(safe(row[column.key]), 48 + index * colWidth, y + 18, {
          maxWidth: colWidth - 10,
        });
      });
      y += 30;
    });
  }

  doc.setTextColor(100, 116, 139);
  doc.setFontSize(9);
  doc.text('Generated by CampusMate', 40, 812);
  doc.save(fileName);
}
